<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray($key, $order, $search=null) {
        $qb = $this->createQueryBuilder('p');
        if (!empty($search)) {
            $qb->where('p.title LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }
        $qry = $qb->addOrderBy('p.'.$key, $order)
            ->getQuery();
        //dump($qry->getSQL());
        return $qry->getArrayResult();
    }
}

